import Head from 'next/head'
import Banner from '../components/banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BD Rangers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      
    </div>
  )
}
